"""Synthetic air traffic for demo mode.

Nothing in this module comes from a live or recorded feed. Every aircraft is
generated from a fixed seed: a fleet shuttles back and forth between real
airport locations along great-circle routes with a simple climb, cruise and
descent profile. Positions are a pure function of time, so the same seed
gives the same sky on every instance and the archive can be backfilled for
replay without storing any third-party data.

Callsigns start with ``DEMO``, registrations with ``SYN-`` and the origin
country is ``Synthetic``, so generated aircraft cannot be mistaken for real
flights in the UI, exports or the API.
"""

from __future__ import annotations

import math
import random
import time
from dataclasses import dataclass
from datetime import datetime, timezone

EARTH_RADIUS_KM = 6371.0
DEMO_SOURCE_LABEL = "Synthetic demo traffic"
DEMO_WARNING = "Demo mode: synthetic flights generated by the app, not real air traffic."
DEMO_AIRLINE_NAME = "Synthetic Demo Air"
DEMO_CALLSIGN_PREFIX = "DEMO"
DEMO_ORIGIN_COUNTRY = "Synthetic"

# Public airport locations (coordinates rounded to ~100 m). Only the
# positions and codes are used, as endpoints for the generated routes.
AIRPORTS: tuple[dict[str, object], ...] = (
    # Poland and central Europe (the app's default map view)
    {"iata": "WAW", "icao": "EPWA", "name": "Warsaw Chopin", "location": "Warsaw", "country_iso2": "PL", "latitude": 52.166, "longitude": 20.967, "region": "europe"},
    {"iata": "KRK", "icao": "EPKK", "name": "Krakow", "location": "Krakow", "country_iso2": "PL", "latitude": 50.078, "longitude": 19.785, "region": "europe"},
    {"iata": "GDN", "icao": "EPGD", "name": "Gdansk", "location": "Gdansk", "country_iso2": "PL", "latitude": 54.378, "longitude": 18.466, "region": "europe"},
    {"iata": "WRO", "icao": "EPWR", "name": "Wroclaw", "location": "Wroclaw", "country_iso2": "PL", "latitude": 51.103, "longitude": 16.886, "region": "europe"},
    {"iata": "KTW", "icao": "EPKT", "name": "Katowice", "location": "Katowice", "country_iso2": "PL", "latitude": 50.474, "longitude": 19.080, "region": "europe"},
    {"iata": "POZ", "icao": "EPPO", "name": "Poznan", "location": "Poznan", "country_iso2": "PL", "latitude": 52.421, "longitude": 16.826, "region": "europe"},
    {"iata": "BER", "icao": "EDDB", "name": "Berlin Brandenburg", "location": "Berlin", "country_iso2": "DE", "latitude": 52.362, "longitude": 13.501, "region": "europe"},
    {"iata": "FRA", "icao": "EDDF", "name": "Frankfurt", "location": "Frankfurt", "country_iso2": "DE", "latitude": 50.033, "longitude": 8.570, "region": "europe"},
    {"iata": "MUC", "icao": "EDDM", "name": "Munich", "location": "Munich", "country_iso2": "DE", "latitude": 48.354, "longitude": 11.786, "region": "europe"},
    {"iata": "HAM", "icao": "EDDH", "name": "Hamburg", "location": "Hamburg", "country_iso2": "DE", "latitude": 53.630, "longitude": 9.988, "region": "europe"},
    {"iata": "PRG", "icao": "LKPR", "name": "Prague", "location": "Prague", "country_iso2": "CZ", "latitude": 50.101, "longitude": 14.260, "region": "europe"},
    {"iata": "VIE", "icao": "LOWW", "name": "Vienna", "location": "Vienna", "country_iso2": "AT", "latitude": 48.110, "longitude": 16.570, "region": "europe"},
    {"iata": "BUD", "icao": "LHBP", "name": "Budapest", "location": "Budapest", "country_iso2": "HU", "latitude": 47.437, "longitude": 19.256, "region": "europe"},
    {"iata": "CPH", "icao": "EKCH", "name": "Copenhagen", "location": "Copenhagen", "country_iso2": "DK", "latitude": 55.618, "longitude": 12.656, "region": "europe"},
    {"iata": "ARN", "icao": "ESSA", "name": "Stockholm Arlanda", "location": "Stockholm", "country_iso2": "SE", "latitude": 59.652, "longitude": 17.919, "region": "europe"},
    {"iata": "HEL", "icao": "EFHK", "name": "Helsinki", "location": "Helsinki", "country_iso2": "FI", "latitude": 60.317, "longitude": 24.963, "region": "europe"},
    {"iata": "OSL", "icao": "ENGM", "name": "Oslo", "location": "Oslo", "country_iso2": "NO", "latitude": 60.194, "longitude": 11.100, "region": "europe"},
    {"iata": "RIX", "icao": "EVRA", "name": "Riga", "location": "Riga", "country_iso2": "LV", "latitude": 56.924, "longitude": 23.971, "region": "europe"},
    {"iata": "VNO", "icao": "EYVI", "name": "Vilnius", "location": "Vilnius", "country_iso2": "LT", "latitude": 54.634, "longitude": 25.288, "region": "europe"},
    {"iata": "AMS", "icao": "EHAM", "name": "Amsterdam Schiphol", "location": "Amsterdam", "country_iso2": "NL", "latitude": 52.309, "longitude": 4.764, "region": "europe"},
    {"iata": "BRU", "icao": "EBBR", "name": "Brussels", "location": "Brussels", "country_iso2": "BE", "latitude": 50.901, "longitude": 4.484, "region": "europe"},
    {"iata": "LHR", "icao": "EGLL", "name": "London Heathrow", "location": "London", "country_iso2": "GB", "latitude": 51.470, "longitude": -0.454, "region": "europe"},
    {"iata": "STN", "icao": "EGSS", "name": "London Stansted", "location": "London", "country_iso2": "GB", "latitude": 51.885, "longitude": 0.235, "region": "europe"},
    {"iata": "DUB", "icao": "EIDW", "name": "Dublin", "location": "Dublin", "country_iso2": "IE", "latitude": 53.421, "longitude": -6.270, "region": "europe"},
    {"iata": "CDG", "icao": "LFPG", "name": "Paris Charles de Gaulle", "location": "Paris", "country_iso2": "FR", "latitude": 49.010, "longitude": 2.548, "region": "europe"},
    {"iata": "ZRH", "icao": "LSZH", "name": "Zurich", "location": "Zurich", "country_iso2": "CH", "latitude": 47.458, "longitude": 8.548, "region": "europe"},
    {"iata": "MXP", "icao": "LIMC", "name": "Milan Malpensa", "location": "Milan", "country_iso2": "IT", "latitude": 45.630, "longitude": 8.723, "region": "europe"},
    {"iata": "FCO", "icao": "LIRF", "name": "Rome Fiumicino", "location": "Rome", "country_iso2": "IT", "latitude": 41.800, "longitude": 12.239, "region": "europe"},
    {"iata": "MAD", "icao": "LEMD", "name": "Madrid Barajas", "location": "Madrid", "country_iso2": "ES", "latitude": 40.472, "longitude": -3.561, "region": "europe"},
    {"iata": "BCN", "icao": "LEBL", "name": "Barcelona", "location": "Barcelona", "country_iso2": "ES", "latitude": 41.297, "longitude": 2.078, "region": "europe"},
    {"iata": "LIS", "icao": "LPPT", "name": "Lisbon", "location": "Lisbon", "country_iso2": "PT", "latitude": 38.774, "longitude": -9.134, "region": "europe"},
    {"iata": "ATH", "icao": "LGAV", "name": "Athens", "location": "Athens", "country_iso2": "GR", "latitude": 37.936, "longitude": 23.947, "region": "europe"},
    {"iata": "IST", "icao": "LTFM", "name": "Istanbul", "location": "Istanbul", "country_iso2": "TR", "latitude": 41.262, "longitude": 28.742, "region": "europe"},
    {"iata": "OTP", "icao": "LROP", "name": "Bucharest Otopeni", "location": "Bucharest", "country_iso2": "RO", "latitude": 44.571, "longitude": 26.085, "region": "europe"},
    {"iata": "SOF", "icao": "LBSF", "name": "Sofia", "location": "Sofia", "country_iso2": "BG", "latitude": 42.697, "longitude": 23.411, "region": "europe"},
    {"iata": "KEF", "icao": "BIKF", "name": "Keflavik", "location": "Reykjavik", "country_iso2": "IS", "latitude": 63.985, "longitude": -22.606, "region": "europe"},
    # Intercontinental hubs
    {"iata": "JFK", "icao": "KJFK", "name": "New York JFK", "location": "New York", "country_iso2": "US", "latitude": 40.640, "longitude": -73.779, "region": "world"},
    {"iata": "ORD", "icao": "KORD", "name": "Chicago O'Hare", "location": "Chicago", "country_iso2": "US", "latitude": 41.978, "longitude": -87.905, "region": "world"},
    {"iata": "ATL", "icao": "KATL", "name": "Atlanta", "location": "Atlanta", "country_iso2": "US", "latitude": 33.637, "longitude": -84.428, "region": "world"},
    {"iata": "LAX", "icao": "KLAX", "name": "Los Angeles", "location": "Los Angeles", "country_iso2": "US", "latitude": 33.942, "longitude": -118.408, "region": "world"},
    {"iata": "SFO", "icao": "KSFO", "name": "San Francisco", "location": "San Francisco", "country_iso2": "US", "latitude": 37.619, "longitude": -122.375, "region": "world"},
    {"iata": "YYZ", "icao": "CYYZ", "name": "Toronto Pearson", "location": "Toronto", "country_iso2": "CA", "latitude": 43.677, "longitude": -79.631, "region": "world"},
    {"iata": "MEX", "icao": "MMMX", "name": "Mexico City", "location": "Mexico City", "country_iso2": "MX", "latitude": 19.436, "longitude": -99.072, "region": "world"},
    {"iata": "GRU", "icao": "SBGR", "name": "Sao Paulo Guarulhos", "location": "Sao Paulo", "country_iso2": "BR", "latitude": -23.432, "longitude": -46.469, "region": "world"},
    {"iata": "DXB", "icao": "OMDB", "name": "Dubai", "location": "Dubai", "country_iso2": "AE", "latitude": 25.253, "longitude": 55.364, "region": "world"},
    {"iata": "DOH", "icao": "OTHH", "name": "Doha Hamad", "location": "Doha", "country_iso2": "QA", "latitude": 25.273, "longitude": 51.608, "region": "world"},
    {"iata": "CAI", "icao": "HECA", "name": "Cairo", "location": "Cairo", "country_iso2": "EG", "latitude": 30.122, "longitude": 31.406, "region": "world"},
    {"iata": "JNB", "icao": "FAOR", "name": "Johannesburg", "location": "Johannesburg", "country_iso2": "ZA", "latitude": -26.139, "longitude": 28.246, "region": "world"},
    {"iata": "DEL", "icao": "VIDP", "name": "Delhi", "location": "Delhi", "country_iso2": "IN", "latitude": 28.556, "longitude": 77.100, "region": "world"},
    {"iata": "SIN", "icao": "WSSS", "name": "Singapore Changi", "location": "Singapore", "country_iso2": "SG", "latitude": 1.364, "longitude": 103.991, "region": "world"},
    {"iata": "HKG", "icao": "VHHH", "name": "Hong Kong", "location": "Hong Kong", "country_iso2": "HK", "latitude": 22.308, "longitude": 113.918, "region": "world"},
    {"iata": "PEK", "icao": "ZBAA", "name": "Beijing Capital", "location": "Beijing", "country_iso2": "CN", "latitude": 40.080, "longitude": 116.585, "region": "world"},
    {"iata": "NRT", "icao": "RJAA", "name": "Tokyo Narita", "location": "Tokyo", "country_iso2": "JP", "latitude": 35.765, "longitude": 140.386, "region": "world"},
    {"iata": "SYD", "icao": "YSSY", "name": "Sydney", "location": "Sydney", "country_iso2": "AU", "latitude": -33.946, "longitude": 151.177, "region": "world"},
)

# Busier airports get more generated routes, like real hubs do.
HUB_WEIGHTS = {
    "WAW": 6, "KRK": 3, "GDN": 2, "KTW": 2, "WRO": 2, "FRA": 5, "MUC": 4, "AMS": 5,
    "LHR": 6, "CDG": 5, "IST": 4, "MAD": 3, "BCN": 3, "FCO": 3, "VIE": 3, "CPH": 3,
    "ZRH": 3, "HEL": 2, "ARN": 2, "BER": 3, "PRG": 2, "BUD": 2,
}

SHORT_HAUL_TYPES = ("A320", "A20N", "B738", "B38M", "A21N", "E195", "E190", "AT76", "DH8D", "A319")
LONG_HAUL_TYPES = ("B789", "B77W", "A359", "A333", "B788", "A388", "A35K")


@dataclass(frozen=True, slots=True)
class SyntheticFlight:
    icao24: str
    callsign: str
    registration: str
    type_code: str
    origin: dict[str, object]
    destination: dict[str, object]
    distance_km: float
    cruise_speed_kmh: float
    cruise_altitude_m: float
    leg_seconds: float
    turnaround_seconds: float
    phase_offset_seconds: float

    @property
    def cycle_seconds(self) -> float:
        return 2 * (self.leg_seconds + self.turnaround_seconds)


def _to_vector(latitude: float, longitude: float) -> tuple[float, float, float]:
    lat = math.radians(latitude)
    lon = math.radians(longitude)
    return (math.cos(lat) * math.cos(lon), math.cos(lat) * math.sin(lon), math.sin(lat))


def great_circle_km(a: dict[str, object], b: dict[str, object]) -> float:
    lat1, lon1 = math.radians(float(a["latitude"])), math.radians(float(a["longitude"]))
    lat2, lon2 = math.radians(float(b["latitude"])), math.radians(float(b["longitude"]))
    h = (
        math.sin((lat2 - lat1) / 2) ** 2
        + math.cos(lat1) * math.cos(lat2) * math.sin((lon2 - lon1) / 2) ** 2
    )
    return 2 * EARTH_RADIUS_KM * math.asin(min(1.0, math.sqrt(h)))


def interpolate_great_circle(
    a: dict[str, object],
    b: dict[str, object],
    fraction: float,
) -> tuple[float, float]:
    """Return (latitude, longitude) at ``fraction`` of the way from a to b."""
    va = _to_vector(float(a["latitude"]), float(a["longitude"]))
    vb = _to_vector(float(b["latitude"]), float(b["longitude"]))
    dot = max(-1.0, min(1.0, sum(x * y for x, y in zip(va, vb))))
    omega = math.acos(dot)
    if omega < 1e-9:
        return float(a["latitude"]), float(a["longitude"])
    sin_omega = math.sin(omega)
    wa = math.sin((1 - fraction) * omega) / sin_omega
    wb = math.sin(fraction * omega) / sin_omega
    x, y, z = (wa * pa + wb * pb for pa, pb in zip(va, vb))
    latitude = math.degrees(math.atan2(z, math.hypot(x, y)))
    longitude = math.degrees(math.atan2(y, x))
    return latitude, longitude


def initial_bearing(latitude: float, longitude: float, target: dict[str, object]) -> float:
    lat1, lon1 = math.radians(latitude), math.radians(longitude)
    lat2, lon2 = math.radians(float(target["latitude"])), math.radians(float(target["longitude"]))
    d_lon = lon2 - lon1
    x = math.sin(d_lon) * math.cos(lat2)
    y = math.cos(lat1) * math.sin(lat2) - math.sin(lat1) * math.cos(lat2) * math.cos(d_lon)
    return (math.degrees(math.atan2(x, y)) + 360.0) % 360.0


def build_fleet(flight_count: int, seed: int) -> tuple[SyntheticFlight, ...]:
    rng = random.Random(seed)
    europe = [airport for airport in AIRPORTS if airport["region"] == "europe"]
    world = [airport for airport in AIRPORTS if airport["region"] == "world"]
    europe_weights = [HUB_WEIGHTS.get(str(airport["iata"]), 1) for airport in europe]
    fleet: list[SyntheticFlight] = []

    while len(fleet) < max(flight_count, 0):
        roll = rng.random()
        if roll < 0.72:
            origin, destination = rng.choices(europe, weights=europe_weights, k=2)
        elif roll < 0.9:
            origin = rng.choices(europe, weights=europe_weights, k=1)[0]
            destination = rng.choice(world)
        else:
            origin, destination = rng.sample(world, 2)

        distance_km = great_circle_km(origin, destination)
        if origin is destination or distance_km < 250:
            continue

        index = len(fleet)
        long_haul = distance_km > 3000
        cruise_speed_kmh = rng.uniform(820, 910) if long_haul else rng.uniform(700, 820)
        cruise_altitude_m = (
            rng.choice((10360, 10970, 11580, 12190))
            if long_haul
            else rng.choice((8530, 9140, 10060, 10670, 11280))
        )
        leg_seconds = distance_km / cruise_speed_kmh * 3600 + 15 * 60
        turnaround_seconds = rng.uniform(60, 100) * 60 if long_haul else rng.uniform(20, 40) * 60
        cycle_seconds = 2 * (leg_seconds + turnaround_seconds)
        fleet.append(
            SyntheticFlight(
                icao24=f"{0x5E0000 + index:06x}",
                callsign=f"{DEMO_CALLSIGN_PREFIX}{index + 1:03d}",
                registration=f"SYN-{index + 1:04d}",
                type_code=rng.choice(LONG_HAUL_TYPES if long_haul else SHORT_HAUL_TYPES),
                origin=origin,
                destination=destination,
                distance_km=distance_km,
                cruise_speed_kmh=cruise_speed_kmh,
                cruise_altitude_m=float(cruise_altitude_m),
                leg_seconds=leg_seconds,
                turnaround_seconds=turnaround_seconds,
                phase_offset_seconds=rng.uniform(0, cycle_seconds),
            )
        )

    return tuple(fleet)


def flight_leg_at(flight: SyntheticFlight, timestamp: float) -> tuple[dict, dict, float | None]:
    """Return (from, to, fraction flown) at ``timestamp``; fraction is None on the ground at ``to``."""
    phase = (timestamp + flight.phase_offset_seconds) % flight.cycle_seconds
    if phase < flight.leg_seconds:
        return flight.origin, flight.destination, phase / flight.leg_seconds
    phase -= flight.leg_seconds
    if phase < flight.turnaround_seconds:
        return flight.origin, flight.destination, None
    phase -= flight.turnaround_seconds
    if phase < flight.leg_seconds:
        return flight.destination, flight.origin, phase / flight.leg_seconds
    return flight.destination, flight.origin, None


def flight_state_at(flight: SyntheticFlight, timestamp: float) -> dict[str, object]:
    departure, arrival, fraction = flight_leg_at(flight, timestamp)
    base = {
        "icao24": flight.icao24,
        "callsign": flight.callsign,
        "origin_country": DEMO_ORIGIN_COUNTRY,
        "registration": flight.registration,
        "type_code": flight.type_code,
        "last_contact": int(timestamp),
        "synthetic": True,
    }

    if fraction is None:
        return {
            **base,
            "latitude": round(float(arrival["latitude"]), 5),
            "longitude": round(float(arrival["longitude"]), 5),
            "true_track": None,
            "altitude": 0.0,
            "velocity": 0.0,
            "vertical_rate": 0.0,
            "on_ground": True,
        }

    latitude, longitude = interpolate_great_circle(departure, arrival, fraction)
    flown_km = fraction * flight.distance_km
    remaining_km = flight.distance_km - flown_km
    climb_km, descent_km = 180.0, 230.0
    climb_ratio = min(1.0, flown_km / climb_km)
    descent_ratio = min(1.0, remaining_km / descent_km)
    altitude = flight.cruise_altitude_m * min(climb_ratio, descent_ratio)
    speed_ms = flight.cruise_speed_kmh / 3.6 * (0.55 + 0.45 * min(climb_ratio, descent_ratio))

    if climb_ratio < 1.0 and climb_ratio <= descent_ratio:
        vertical_rate = flight.cruise_altitude_m / (climb_km / (flight.cruise_speed_kmh / 3600) * 0.8)
    elif descent_ratio < 1.0:
        vertical_rate = -flight.cruise_altitude_m / (descent_km / (flight.cruise_speed_kmh / 3600) * 0.8)
    else:
        vertical_rate = 0.0

    return {
        **base,
        "latitude": round(latitude, 5),
        "longitude": round(longitude, 5),
        "true_track": round(initial_bearing(latitude, longitude, arrival), 1),
        "altitude": round(max(altitude, 150.0), 1),
        "velocity": round(speed_ms, 1),
        "vertical_rate": round(vertical_rate, 1),
        "on_ground": False,
    }


def _in_bbox(flight: dict[str, object], bbox: dict[str, float]) -> bool:
    latitude = float(flight["latitude"])
    longitude = float(flight["longitude"])
    if not bbox["lamin"] <= latitude <= bbox["lamax"]:
        return False
    if bbox["lomin"] <= bbox["lomax"]:
        return bbox["lomin"] <= longitude <= bbox["lomax"]
    return longitude >= bbox["lomin"] or longitude <= bbox["lomax"]


class SyntheticTrafficProvider:
    """FlightProvider that generates deterministic synthetic traffic."""

    name = "demo"

    def __init__(self, flight_count: int = 900, seed: int = 20260311, clock=time.time) -> None:
        self.fleet = build_fleet(flight_count, seed)
        self._by_callsign = {flight.callsign: flight for flight in self.fleet}
        self._clock = clock

    def snapshot_at(self, timestamp: float, bbox: dict[str, float]) -> dict[str, object]:
        flights = [
            state
            for state in (flight_state_at(flight, timestamp) for flight in self.fleet)
            if _in_bbox(state, bbox)
        ]
        return {
            "fetched_at": datetime.fromtimestamp(timestamp, tz=timezone.utc).isoformat(),
            "bbox": dict(bbox),
            "count": len(flights),
            "flights": flights,
        }

    def fetch_flights(self, bbox: dict[str, float]) -> dict[str, object]:
        return self.snapshot_at(self._clock(), bbox)

    def find(self, callsign: str | None) -> SyntheticFlight | None:
        if not callsign:
            return None
        return self._by_callsign.get(callsign.strip().upper())

    def current_leg(self, callsign: str | None) -> tuple[dict, dict] | None:
        flight = self.find(callsign)
        if flight is None:
            return None
        departure, arrival, _ = flight_leg_at(flight, self._clock())
        return departure, arrival


def _route_airport(airport: dict[str, object]) -> dict[str, object]:
    return {key: airport[key] for key in ("icao", "iata", "name", "location", "country_iso2", "latitude", "longitude")}


class SyntheticRouteClient:
    """Route lookup for synthetic callsigns; never calls an external service."""

    def __init__(self, provider: SyntheticTrafficProvider) -> None:
        self.provider = provider

    def lookup_route(self, callsign: str, latitude=None, longitude=None) -> dict[str, object] | None:
        leg = self.provider.current_leg(callsign)
        if leg is None:
            return None
        departure, arrival = leg
        airports = [_route_airport(departure), _route_airport(arrival)]
        flight_number = str(callsign).strip().upper()[len(DEMO_CALLSIGN_PREFIX):]
        return {
            "callsign": str(callsign).strip().upper(),
            "airline_code": DEMO_CALLSIGN_PREFIX,
            "airline_name": DEMO_AIRLINE_NAME,
            "flight_number": flight_number,
            "airport_codes": f"{departure['icao']}-{arrival['icao']}",
            "iata_codes": f"{departure['iata']}-{arrival['iata']}",
            "origin": airports[0],
            "destination": airports[-1],
            "stops": [],
            "airports": airports,
            "plausible": True,
            "route_label": f"{departure['iata']} -> {arrival['iata']}",
            "route_verbose": f"{departure['location']} -> {arrival['location']}",
        }


class NoPhotoClient:
    """Photo lookup that never leaves the process; synthetic aircraft have no photos."""

    def fetch_photo(self, registration, **_kwargs) -> None:
        return None
